name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: src/azure-sa
      
    - name: Run ESLint
      run: npm run lint
      working-directory: src/azure-sa
    
    - name: Run tests
      run: npm test
      working-directory: src/azure-sa
      
    - name: Build
      run: npm run build
      working-directory: src/azure-sa
      
    - name: Deploy
      run: echo "Deploy step here"
      working-directory: src/azure-sa
