name: SonarQube Scan
on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0  # Disabling shallow clones is recommended for improving the relevancy of reporting
        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@v4
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}